# This work flow compiles Freetouchdeck for the ESP32 
# Created 29-5-2022
# by Dustin Watts
name: Test Compile for ESP32 on Arduino Core

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    name: Test compiling for ESP32
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout ESP32-BLE-Keyboard library
      uses: actions/checkout@v3
      with:
        repository: T-vK/ESP32-BLE-Keyboard
        ref: master
        path: CustomLibrary_ESP32-BLE-Keyboard 

    - name: Checkout ESPAsyncWebServer library
      uses: actions/checkout@v3
      with:
        repository: me-no-dev/ESPAsyncWebServer
        ref: master
        path: CustomLibrary_ESPAsyncWebServer

    - name: Checkout AsyncTCP library
      uses: actions/checkout@v3
      with:
        repository: me-no-dev/AsyncTCP
        ref: master
        path: CustomLibrary_AsyncTCP

    - name: Checkout Adafruit-GFX-Library library
      uses: actions/checkout@v3
      with:
        repository: adafruit/Adafruit-GFX-Library
        ref: master
        path: CustomLibrary_Adafruit-GFX-Library

    - name: Checkout custom TFT_eSPI library
      uses: actions/checkout@v3
      with:
        repository: DustinWatts/TFT_eSPI
        ref: master
        path: CustomLibrary_TFT_eSPI 
        
    - name: Test compile with Arduino CLI
      uses: ArminJo/arduino-test-compile@v3
      with: 
        arduino-board-fqbn: esp32:esp32:esp32:PartitionScheme=no_ota
        cli-version: 0.22.0
        extra-arduino-cli-args: "--warnings default"
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        required-libraries: ArduinoJson